/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.6.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    `java-library`
}


val jx_browser_version by extra("7.11")

repositories {
    jcenter()
    maven {
        url = uri("https://europe-maven.pkg.dev/jxbrowser/releases")
    }
    maven {
        url = uri("http://maven.teamdev.com/repository/products")
    }
}

dependencies {
    implementation("com.miglayout:miglayout-swing:4.2")
    implementation("com.teamdev.jxbrowser:jxbrowser:$jx_browser_version")
    implementation("com.teamdev.jxbrowser:jxbrowser-win64:$jx_browser_version")
    implementation("com.teamdev.jxbrowser:jxbrowser-linux64:$jx_browser_version")
    implementation("com.teamdev.jxbrowser:jxbrowser-mac:$jx_browser_version")
    implementation("com.teamdev.jxbrowser:jxbrowser-swing:$jx_browser_version")

    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.2")
}

//application {
//    // Define the main class for the application.
//    mainClassName = "com.inductiveautomation.ignition.App"
//}

val test by tasks.getting(Test::class) {
    // Use junit platform for unit tests
    useJUnitPlatform()
}
