/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jxb.dnd.sscee;

import com.inductiveautomation.ignition.App;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appInits() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
